### ISSUE TITLE
Is there a plan/chance to update selenium in Testbench 5.x for Vaadin 8.x?

### ISSUE THREAD

**Issue by Petikoch** [vaadin/testbench#1051]
Hi,

we are using testbench 5.1.1 and face some issues with crashing IEDriverServer.exe's (Internet Explorer 11). We are in a strict enterprise corset and can not switch easily to other browsers (Chrome, Firefox) or browser versions.

Testbench 5.1.1 is based on Selenium 3.4.0, which is from April 2017. There are newer Selenium releases out there with - I hope - a more stable IE Driver.

I see you are working hard to get a 6.0.0 Testbench version ready for Vaadin 10 with the latest Selenium version.

**Is there a plan to upgrade the Selenium version also in testbench 5.x for the Vaadin "current production version" 8?**

Thanks for your time and feedback,
Peti

**Comment by DiegoCardoso** [comment]
Hi, @Petikoch 

Thanks for your question.

We are definitely planning to update Selenium for Testbench 5 to a newer version. But as you pointed out, we are focusing our efforts toward Vaadin 10, and that's why TB 6 is getting more attention. 

We can't promise a date for this update, and I understand that it might not be the answer you would like to hear.

Meanwhile, I think you can workaround this by adding direct dependencies to the desired version of Selenium so the transitive dependency for Selenium 3.4 would be overridden.

**Comment by Petikoch** [comment]
Thanks @DiegoCardoso for your answer. I'll try to override the Selenium version, but  I **guess** there will be binary incompatibilities with Vaadin Testbench 5.1.1. I'll check that...

**Comment by Petikoch** [comment]
Hi @DiegoCardoso , 

**good news**. 

We did override Testbench's transient Selenium dependency in our gradle build to version `3.11.0` and use `IEDriverServer.exe` Version `3.11.1` 

- everything seems to be binary compatible with Testbench `5.1.1` and runs fine
- no more IE crashes (so far)

Best regards,
Peti

**Comment by DiegoCardoso** [comment]
Hi, @Petikoch 

I am glad to hear that it worked as expected. I hope we can go back to that anytime soon. 

Regards,
Diego
