### ISSUE TITLE
Can't select a TextField inside a Designer built template

### ISSUE THREAD

**Issue by mstahv** [vaadin/testbench#1064]
If I use TextField in a design, I can't access it with TestBench. A reduced test case as an attachment.

[my_starter_project-5 2.zip](https://github.com/vaadin/testbench/files/2003827/my_starter_project-5.2.zip)

**Comment by alvarezguille** [comment]
Because of shadow DOM it's not possible to query elements from the document context, in your project there's a custom element `matti-design` with a shadow root that contains the textfield.

The simplest solution to what the test is trying to do is to query for the `matti-design` element and use it as a context for getting the textfield, which would look like this:
`$("matti-design").first().$(TextFieldElement.class).first().setValue("Jorma");`

A bit more complex option is to use a [page object for the template](https://vaadin.com/docs/v10/testbench/testbench-maintainable-tests-using-page-objects.html)
The page object for `matti-design` would looks like this:
```
@Element("matti-design")
public class MattiDesignElement extends TestBenchElement {

    public void setFieldValue(String newValue) {
        getField().setValue(newValue);
    }

    TextFieldElement getField() {
        return $(TextFieldElement.class).first();
    }
}
```
and the setValue in the test would looks like this
` $(MattiDesignElement.class).first().setFieldValue("Jorma");`


`$("matti-design")` and ` $(MattiDesignElement.class)` are equivalent, the first one with String tagName param is just a helper to avoid creating new TestBenchElement classes when it's only needed for querying.

**Comment by mstahv** [comment]
I can see the technical reason now, but from end users point of view that is totally broken.

Some ideas:

 * Could TB just deal this?
 * Could the template( or especially Designer generated template) work without shadow root?

cc: @ripla

**Comment by johannesh2** [comment]
I guess the reason for not doing a full tree traverse was performance (was it so @Artur-?). There is this https://github.com/vaadin/testbench/issues/954 for implementing something similar.

**Comment by Artur-** [comment]
#954 would "fix" this although I don't think it should be on by default to avoid surprises when you find many elements with the same `id` etc

**Comment by johannesh2** [comment]
In that case it will not fix the expectation, that everything "just works" from document root without thinking about it in the same way V8 did. Closing this as wontfix.

**Comment by johannesh2** [comment]
Just have to add for the record, that the expectation is a valid one, but I don't want to leave this ticket hanging in the backlog if we are not going to fix it in the very near future in 6.x releases.

**Comment by mstahv** [comment]
If you are not going to fix this, you should  emphasis this in the documentation. That isn't enough, but at least you could point people to a right place when they come to you with WTFs.

**Comment by johannesh2** [comment]
You are right. I created #1074
