### ISSUE TITLE
When updating from 12.0.0 to 12.0.3 ComboBoxElement throws exceptions when using select by text

### ISSUE THREAD

**Issue by brp-benjamin** [vaadin/testbench#1124]
ComboBoxElement.selectByText throws IllegalArgumentException.

Clientside the component still selects the supplied text but the ComboBoxElement throws an exception anyway.

**Comment by voodoohoo** [comment]
+1
Same here `java.lang.IllegalArgumentException: Value 'EzIOn' not found in the combobox` but value does exists in combobox

![image](https://user-images.githubusercontent.com/3798979/51110687-cc190c80-17f9-11e9-9d7c-4bef919f9dbc.png)

**Comment by DiegoCardoso** [comment]
Hello, thanks for this report.

While taking a look at this we found that the source of the error is the ComboBox itself as being described in this open issue https://github.com/vaadin/vaadin-combo-box-flow/issues/182.

There's a fix in progress for this issue, so hopefully we will see this issue gone in the next release.

Meanwhile, you can workaround this issue by setting ComboBox webjar version to `4.2.0` in your project:

```xml
<dependency>
    <groupId>org.webjars.bowergithub.vaadin</groupId>
    <artifactId>vaadin-combo-box</artifactId>
    <version>4.2.0</version>
</dependency>
```

We will leave this issue opened, so we can track whether we need to add some changes or not to the `ComboBoxElement` in TB.

**Comment by DiegoCardoso** [comment]
[Vaadin 12.0.6](https://github.com/vaadin/platform/releases/tag/12.0.6) was released yesterday with Vaadin Combo Box (Flow integration 2.0.3, web component v4.2.3), so you should see the issue gone by upgrading the platform.

This version contains the fix for the filter bug (https://github.com/vaadin/vaadin-combo-box-flow/commit/b286c5b52db3da8736b4aef090e5da8d4028e9e9).

I am closing this issue, but please re-open it in case the bug is still present.
