### ISSUE TITLE
Fusion: Have a new TestBench release that uses Selenium 4

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/testbench#1279]
As a developer, I want to use the new API in Selenium 4 for [sending CDP (Chrome DevTools Protocol) commands](https://applitools.com/blog/selenium-4-chrome-devtools/), so that I can simulate the offline situation with code like
```
        DevTools devTools = chromeDriver.getDevTools();
        devTools.createSession();
        devTools.send(Network.emulateNetworkConditions(
                true, // offline flag
                0, // latency
                -1, // download throttling
                -1, // upload throttling 
                Optional.empty()
        ));
```
DoD:
A new TestBench version that uses Selenium 4.

**Comment by khmarbaise** [comment]
Hi, we are currently using vaadin-testbench (14.8.0) and I've tried to upgrade the selenium part to 4.1.0 which unfortunately does not work because testbench itself uses internal classes of selenium (3.14..) 

The base class `TestBenchElement` use the `WrapsElement` which is an internal class of selenium...

```java
..
import org.openqa.selenium.internal.WrapsElement;
.
public class TestBenchElement implements WrapsElement, WebElement, HasDriver,
        CanCompareScreenshots, HasTestBenchCommandExecutor, HasElementQuery,
        HasPropertySettersGetters, HasCallFunction {
```

It looks like this is one of the issue that prevents using selenium 4.X with Testbench...

**Comment by Artur-** [comment]
TestBench 8 is based on Selenium 4. The beta version is part of Vaadin 23 beta today.
