### ISSUE TITLE
[uitest] Improve generic usage

### ISSUE THREAD

**Issue by knoobie** [vaadin/testbench#1401]
Instead of 

```java
GridWrap<Grid<SamplePerson>, SamplePerson> grid_ = $(Grid.class).first();
```

What would you think of: 

```java
var grid_ = $(Grid.class, SamplePerson.class).first();
```

or 

```java
var grid_ = $(Grid.class).withType(SamplePerson.class).first();
```

because people often use the `var` from java 11 and above, making the search a little bit more readable in my opinion

This could also help to make sure that the grid with proper generic type is returned, or more important if you e.g. query the appearance of multiple combo boxes where each has a unique enum allowing for quick search by type instead of a "fast changing" thing like a label

---- 

Comment by @mcollovati from the original discussion:

> Good suggestion, it needs to be investigated.
At a first glance such a feature may require having wrapper type as generic parameter for ComponentQuery and overloads of $(componentType, itemType) for every generic component (something similar to what is in the mixin interface for wrappers PR https://github.com/vaadin/testbench/pull/1386)

**Comment by mcollovati** [comment]
Searching for components and getting the tester are now completely separated.
With ComponentQuery it is not possible at the moment infer value type for components like Grid; you will always obtain a `Grid`, not a `Grid<Something>`.
But we can extend the `test()` factory method for such components so that the tester will have correct type.
So we can have this working solution

```
var g = $(Grid.class).first();
var row = test(g, SamplePerson.class).getRow(1);
Assertions.assertEquals("XYZ", row.getFirstName());

String firstName = test($(Grid.class).first(), SamplePerson.class).getRow(1).getFirstName();
Assertions.assertEquals("XYZ", row.getFirstName());
```
