### ISSUE TITLE
Support parameterized @BrowserTest methods

### ISSUE THREAD

**Issue by Artur-** [vaadin/testbench#1644]
If you try to combine `@BrowserTest` and `@ParameterizedTest` like
```
public class MyIT extends BrowserTestBase {

@ParameterizedTest
@ValueSource(strings = { "user1", "user2" })
@BrowserTest
public void testLogin(String input) { 
     //      ...
}
```

Your test will not run because of
```
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [com.vaadin.testbench.browser.BrowserTestInfo arg0] in method [public void com.vaadin.testbench.BrowserTestBase.setBrowserTestInfo(com.vaadin.testbench.browser.BrowserTestInfo)].
```

**Comment by MarcinVaadin** [comment]
Assigned myself not to forget in future, feel free to reassign.

**Comment by mcollovati** [comment]
ParameterizedTest and BrowserTest are both template extensions, and currently "two `@TestTemplate` implementations cannot be executed at the same time for a single method" (https://github.com/junit-team/junit5/issues/1224#issuecomment-355303637)

I suppose that to provide such a feature, a custom `@ParameterizedBrowserTest` (annotation + extension) should be implemented (unfortunately, `ParameterizedTestExtension` class is package protected)

**Comment by mcollovati** [comment]
Since `@BrowserTest` and `@ParameterizedTest` cannot be applied at the same time, I thought about a couple of different approaches
- extend `ParameterizedTestExtension` to create a matrix with the required browsers to test: not possible because all `ParameterizedTestExtension` and related classes are package protected
- new extension class encapsulating both `MultipleBrowsersExtension` and `ParameterizedTestExtension` (using reflection): could create the matrix, but internally `ParameterizedTestExtension` assumes test method is annotated with `@ParameterizedTest`; if it is not, it doesn't work and there are no ways to work around the problem.
- copy/paste of the `ParameterizedTestExtension` class and related classes (or instantiate via reflection if possible): a lot of code that needs to be maintained and aligned with the original extension.
- copy/paste from `ParameterizedTestExtension` only the code that collects the arguments and extend `MultipleBrowsersExtension` to handle them: maybe less code to maintain, but still a hacky solution.


Alternative: if we accept to run the test for a single browser, we can make `BrowserExtension` work with `@ExtendWith` (provide a no-args constructor, define a way to specify the browser, ...) and introduce a new annotation `@ParameterizedBrowserTest` that will be meta-annotated with `@ParameterizedTest`.
As an example, if `BrowserExtension` is instantiated without providing the `Capabilities`, it could take the first item of `CapabilitiesUtil.getDesiredCapabilities(...)`.

**Comment by mcollovati** [comment]
Otherwise, we should wait for https://github.com/junit-team/junit5/issues/871
