### ISSUE TITLE
Add a Tester class for VirtualList component

### ISSUE THREAD

**Issue by mshabarov** [vaadin/testbench#1721]
Create a [Tester](https://github.com/vaadin/testbench/blob/main/vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/ComponentTester.java) class for [VirtualList](https://github.com/vaadin/flow-components/tree/main/vaadin-virtual-list-flow-parent)

**Comment by joelpop** [comment]
What methods should `VirtualListTester` support?

Because `VirtualList` is really just a display component (non-interactive), there won't be any methods to set, clear, or select things. Looking at the non-interactive methods of `GridTester` for inspiration, candidate methods to consider supporting are:
- `int size()`
- `T getItem(int index)` 
- `String getItemText(int index)`
- `Component getItemComponent(int index)`
- `<V> V getLitRendererPropertyValue(int index, String propertyName, Class<V> propertyClass)
- `<V> V invokeLitRendererFunction(int index, String functionName)

In order to support the latter two, `VirtualList` must be changed to implement and publicly expose a `getRenderer` method as `Grid` does.

Please provide your thoughts on what methods should or shouldn't be provided by this tester.

**Comment by MatthewVaadin** [comment]
At least for the use cases we require, the last two methods would not be necessary. The rest of the API looks perfect for the tests we want to write.
