### ISSUE TITLE
Release date of 5.1.0?

### ISSUE THREAD

**Issue by Petikoch** [vaadin/testbench#918]
Hi,

we are using testbench 5.0.0 and face some issues with crashing `IEDriverServer.exe`'s ;-)
We'd like to update selenium in hope to get more stable tests. 

When do you plan to release 5.1.0? 

Or can we bump selenium independent from testbench without breaking testbench?

Thanks for your time & best regards,
Peti

**Comment by DiegoCardoso** [comment]
Hi, @Petikoch. 

Sorry for the delay to answer you.

About the first question, we are planning to release at least a beta version for 5.1.0 soon. Currently we have an open PR (#919), which might get into this version, and brings a newer Selenium version to TB.

Regarding the second question, I am not sure if changing Selenium version would break TB, but as it is a bit of time since you asked, please let me know if you still need help with that.

**Comment by Petikoch** [comment]
@DiegoCardoso any update of a regular 5.1 release soon?

**Comment by DiegoCardoso** [comment]
Hi, @Petikoch. 

Thanks for asking.

We are planning to release 5.1 final later this week.

**Comment by Petikoch** [comment]
https://github.com/vaadin/testbench/releases/tag/5.1.0

Wooot! :-)
